export type ValidSkills =
  | "TypeScript"
  | "Java"
  | "C#"
  | "Go"
  | "SQL"
  | "NestJS"
  | "Express"
  | "Java Spring"
  | ".NET Core"
  | "ReactJS"
  | "Node.js"
  | "AWS"
  | "Docker"
  | "Linux"
  | "PostgreSQL"
  | "MySQL"
  | "Redis"
  | "MQTT"
  | "Socket.io"
  | "Git"
  | "Unit Testing"
  | "Integration Testing"
  | "Postman"
  | "REST API"
  | "Microservices"
  | "Next.js"
  | "MongoDB"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "Tailwind CSS"
  | "GraphQL"
  | "Framer Motion";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "IoT"
  | "Fintech"
  | "Healthcare"
  | "GIS";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume";
