export const siteConfig = {
  name: "Suryo Hastomo - Applied AI Engineer",
  authorName: "Suryo Hastomo",
  username: "soerjo",
  description:
    "Suryo Hastomo - Backend Engineer Explore my projects, experience, and contributions in software development and AI.",
  url: "https://your-actual-domain.com",
  links: {
    twitter: "https://x.com/suryohastomo",
    github: "https://github.com/soerjo",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },
  ogImage: "/profile-img.jpg",
  iconIco: "/logo.png",
  logoIcon: "/logo.png",
  keywords: [
    "Suryo Hastomo",
    "Applied AI Engineer",
    "AI Engineer",
    "Software Engineer",
    "Full Stack Developer",
    "Machine Learning",
    "Data Engineering",
    "UBS",
    "Python Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "Databricks",
    "AI Startups",
    "Software Development",
    "Web Developer",
    "Backend Developer",
    "Frontend Developer",
    "Tech Portfolio",
  ],
};
