export const siteConfig = {
  name: "Suryo Hastomo - Backend Engineer",
  authorName: "Suryo Hastomo",
  username: "soerjo",
  description:
    "Suryo Hastomo - Backend Engineer specializing in TypeScript, .NET, Java, and Go. Experience building scalable, high-availability systems across healthcare, fintech, GIS, and IoT industries.",
  url: "https://soerjo.github.io",
  links: {
    twitter: "https://twitter.com/soerj0",
    github: "https://github.com/soerjo",
    templateRepo: "https://github.com/namanbarkiya/minimal-next-portfolio",
  },
  ogImage: "/profile-img.jpg",
  iconIco: "/logo.png",
  logoIcon: "/logo.png",
  keywords: [
    "Suryo Hastomo",
    "Backend Engineer",
    "Software Engineer",
    "TypeScript",
    "NestJS",
    ".NET Core",
    "Java",
    "Go",
    "Microservices",
    "API Design",
    "System Architecture",
    "PostgreSQL",
    "Redis",
    "Docker",
    "AWS",
    "Indonesia",
    "Remote Engineer",
  ],
};
